apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  # ClusterIP = solo accesible dentro del cluster
  # El frontend lo llama por nombre DNS: http://backend:3000
  type: ClusterIP