apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: BACKEND_URL
              # Kubernetes DNS resuelve "backend" al ClusterIP del Service backend
              # Formato: <service-name>.<namespace>.svc.cluster.local
              value: "http://backend.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.backend.port }}"
              {{- range $key, $value := .Values.frontend.env }}
              - name: {{ $key }}
                value: "{{ $value }}"
              {{- end }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}