apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice-demo-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    # Indica al LBC que este Ingress es suyo para procesar
    kubernetes.io/ingress.class: alb

    # internet-facing = ALB en subnets públicas con IP pública
    # internal = ALB en subnets privadas (para APIs internas)
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}

    # ip = el ALB apunta directamente a IPs de pods (requiere VPC CNI)
    # instance = el ALB apunta a IPs de nodos + NodePort (forma antigua)
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType }}

    # Puerto de entrada del ALB
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80